### ISSUE TITLE
eventsByTag query returns incorrect results for tags that share a prefix

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-persistence-jdbc#168]
The query for `eventsByTag` uses a `LIKE` to do a substring match on the provided tag:

https://github.com/dnvriend/akka-persistence-jdbc/blob/8a3ad9556ca5ccfbaec11f2b5c3bc39b39bd054a/src/main/scala/akka/persistence/jdbc/query/dao/ByteArrayReadJournalDao.scala#L97-L110

This means that if you use tags that contain a shard number, you'll have conflicts with more than single-digit shards. For example, when there is a tag such as `JobEvent12`, it will be matched by queries for `JobEvent1`.

**Comment by renatocaval** [comment]
I can see only two solutions here:

1. add a flag to swap between `=` and `LIKE` syntax. 
2. add more tag columns and use `=` syntax, ie: "tag1 =  'JobEvent1' OR tag2 = 'FooBar'"

Option 1 is a damm hack and will also force people to stick with one tag only. 

Option 2 is better but is backward incompatible. 

Any other more creative ideas?

**Comment by TimMoore** [comment]
I was thinking something like this:

```scala
val startsWithTag = s"$tag,%"
val endsWithTag = s"%,$tag"
val containsTag = s"%,$tag,%"

// ...
    WHERE (
      "#$tags" = $tag OR
      "#$tags" LIKE $startsWithTag OR
       "#$tags" LIKE $endsWithTag OR
      "#$tags LIKE containsTag
    ) AND
// ...
```

I don't know if that's going to cause terrible query performance, however. It might be better to have an exploded tags table with a foreign key relation to the persistence ID that is written in a transaction with the journal table, then join them to query. That of course would be a massive change requiring a schema migration.

**Comment by TimMoore** [comment]
Possible that the query already requires a full table scan, however... I've never checked.

**Comment by renatocaval** [comment]
> val startsWithTag = s"$tag,%"
val endsWithTag = s"%,$tag"
val containsTag = s"%,$tag,%"

That's indeed creative! I like it. :-) 

Not sure about the performance implications of it.

**Comment by TimMoore** [comment]
You can tell I spent some past time as a Perl programmer :joy:

**Comment by bpiper** [comment]
If you lead with a wildcard in just one of those predicates then it's going to do a full table scan, and looking at how often the journal table is queried (i.e. constantly), this would eventually bring things to a grinding halt.  I'm fairly new to Akka Persistence and Lagom so I'm not sure under what circumstances you'd have multiple tags, but maybe in a lot of cases there's only one, and thus a flag to opt in to equality predicates might not be such a bad idea.

As Tim mentioned, a child table (e.g. `journal_tags`) would be a better option.  Slightly slower for small data volumes, but dramatically faster for large volumes.  Having said that, in the way that we are currently using Lagom (not sure if there are other/better ways of using it), the tag is just a fully qualified event class name with a shard number right at the end.  With a btree index, this may mean reading a lot of index blocks for rows belonging to other shards, which is sub-optimal.  If the concept of sharding was fully supported in the relational data model, then the shard could be its own column, and a composite index (on tag and shard) may perform even better.

**Comment by TimMoore** [comment]
Yes, that's what I was thinking @bpiper, but the existing query also has a leading wildcard:

```scala
       val theTag = s"%$tag%" 
// ...
               WHERE "#$tags" LIKE $theTag 
```

So it might be no worse.

But I agree that multiple tags are uncommon. That could be the best compromise for the time being. I'd suggest that we have the config disable multiple tag support entirely, fail fast when persisting multiple tags, and maybe warn or even fail when deserializing events with multiple tags.

Interesting idea about supporting shards directly in the data model, but right now Akka Persistence has no built-in concept of sharding, only generic tagging. I'll raise it with the Akka team.

**Comment by TimMoore** [comment]
CC @patriknw

**Comment by patriknw** [comment]
It’s perfectly fine for a persistence plugin to define additional custom queries, such as the tag+shardId that you were talking about.

Isn’t the right rdb way to define the tags in a separate table and join to support multiple tags?

**Comment by ignasi35** [comment]
> I'd suggest that we have the config disable multiple tag support entirely, fail fast when persisting multiple tags, and maybe warn or even fail when deserializing events with multiple tags.

+1

**Comment by WellingR** [comment]
There was an issue about this before and at that time we added it to the scaladoc of the eventsByTag methods. So this is a documented limitation.

Joining in a separate table would probably the best solution, however this requires a ddl change.

Logged #172 for the suggestion above

**Comment by WellingR** [comment]
> If you lead with a wildcard in just one of those predicates then it's going to do a full table scan, and looking at how often the journal table is queried (i.e. constantly), this would eventually bring things to a grinding halt.

This is not the only part of the query, there is also a filtering for the ordering column (pk) which should be larger than some value. and there is a limit to the max number of result. So unless you search for a non-exising tag, the whole table will probably not be scanned.

**Comment by bpiper** [comment]
Ah, right you are @WellingR , I'd skimmed over that part of the query the first time around.  It's not the primary key, but there is a unique index on it.  If its bounds are generally pretty tight then yes it should just be range scanning that index and doing table lookups, which makes the discrimination on tag pretty irrelevant (in terms of performance anyway).  The limit would also help in theory too since the order by is on the ordering column.

**Comment by WellingR** [comment]
Even though a separate table to join the tags would be a proper solution. It should actually be possible to keep on using the current LIKE query to retrieve possibly matching journal rows.
We can split the tag string based on the configured separator character, and verify if the tag is actually  a match.

I am investigating if we can simply drop the events after deserializing them with the tags. I still need to investigate if the `hasMoreEvents` thing we are doing might cause problems. (it seems not).

**Comment by WellingR** [comment]
I have been thinking about this.
The proper solution would be to create a separate table journal_tag which joins journal entries with their tags. However there are two reasons why I am not in favour of this:
- First of all we need to change the ddl. Migration might be fairly complex, because we need scripts that retrieve the existing tags column data, and parses it to find all tags inside it.
- Secondly, I think this will hurt our write-performance. Since we need to generate an id which is used both for the journal row, and the journal_tag row(s). Caching seems an option, however if this plugin is used in a clustered environments the caching might cause events to go out of order.

An alternative solution is the following;

We can define a custom query `eventsByExactTags(tags: Set[String], offset: Offset)`
This query works similarly to events by tag, however it returns the events where the value in the tags column is an exact match of any of the given tags.

What do you all thing about this?

**Comment by renatocaval** [comment]
Maybe we don't need to force any migration. How events are persistented is a matter of how the DAO saves them. 

Because we have a DAO layer, we can investigate the option of swapping implementations. If someone wants to save many tags in a different table and pay the performance price, then they can configure the plugin to do so. 

The default DAO must stay the one we have now, but we could eventually also add the option to warn (and eventually) block the usage of many tags.

**Comment by WellingR** [comment]
Since we need to force a migration as part of #180 we might just as well include the proper fix for this issue: a separate table for the tags in the journal.

**Comment by TimMoore** [comment]
Since nobody has had a chance to make the proper fix for this yet, maybe it's worth implementing one of the quick & dirty fixes that doesn't require schema changes?

**Comment by TJSomething** [comment]
If anyone's looking for a quick workaround and is using Postgres, I came up with [a workaround](https://github.com/dnvriend/akka-persistence-jdbc/issues/194#issuecomment-455759027) that fixes this and, by adding an index, improves performance.

**Comment by patriknw** [comment]
The workaround is in place. We'll look at a better schema later.

**Comment by octonato** [comment]
There is now a definitive fix for that (not workaround). Tags are added to a separate table allowing for one-to-many relations. See #467.
