### ISSUE TITLE
Option to auto create tables

### ISSUE THREAD

**Issue by jroper** [akka/akka-persistence-jdbc#69]
It would be very convenient for users in development and testing (and perhaps even in production) if akka-persistence-jdbc offered the option to auto create tables if they don't exist.  akka-persistence-cassandra offers this for example:

https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/resources/reference.conf#L52

Slick can automagically generate and execute database specific DDL, so this shouldn't be too hard.  I'd imagine it would be sufficient to simply check if each table exists first, and if it doesn't execute the create.  To deal with cluster scenarios with two nodes creating the tables at once, if the creation fails you could then check if the table has been created after the failure, and if it has then assume the failure was because another node created it at the same time and so ignore it, otherwise rethrow.

**Comment by dnvriend** [comment]
Hi! This seems like a good addition to the plugin. If you feel up to it, you could make the change and do a PR.

**Comment by jroper** [comment]
I'm currently implementing this myself in Lagom, it probably won't be hard to move what I've got to here once I'm finished.

There are a few things to consider though, firstly you have to detect whether the tables are already created, this turns out to be a little harder than it sounds (if you get a list of tables, they may have a schema in them which could be the current schema, so you need to have some dialect specific way to work out the current schema to do the matching).  You also need to deal with multiple nodes creating the tables at the same time, one possibility is to use a cluster singleton to create them, another is if creation fails, check if the tables exist after the failure, and if they do, ignore the failure.

**Comment by Fristi** [comment]
I also wanted this in a project. I am using single node with h2 (in mem atm) for testing. It seems the current schema will hang upon creation with the combo of h2 and slick

There are two problems
- Snapshot schema uses `O.AutoInc` on two columns and the combination slick + h2 seems to dislike that
- Journal uses `O.AutoInc` in conjunction with primary key which also causes to hang. Because `O.AutoInc` is a primary key automatically (https://github.com/slick/slick/issues/763)

I copied the schema sources and removed these lines and it solved it for me :-).

As @jroper states, in a production environment with a real DB this would cause issues, but just posting this for a head up.

**Comment by dnvriend** [comment]
@Fristi Thanks for the head up!

**Comment by stevemyers** [comment]
I used Slick to create my H2 akka-persistence-jdbc schema, I know it's not a full solution but works good for me as an interim solution.  See gist [here](https://gist.github.com/stevemyers/de1fe4db29555eaea83fa1df3d13a5af)

**Comment by PerWiklander** [comment]
Isn't this implemented already? I always start with an empty schema in dev and the required tables (journal) show up by themselves.

**Comment by cristianrgreco** [comment]
I've also run into this issue now using SQLite. Writing to the journal fails with an error saying that the `snapshot` table does not exist.

**Comment by NicolasRouquette** [comment]
I developed a multi-service Lagom 1.4.11 application that I wanted to configure for either Cassandra or MySQL persistence. There is a helpful blog article and example for a single service with a single MySQL persistence database here: https://blog.knoldus.com/a-crud-application-lagom-es-cqrs-with-mysql/

In my case, I wanted to mimic the recommendation from the doc for Cassandra persistence to have each service use a distinct Cassandra keyspace; for MySQL persistence, this means each service uses a distinct MySQL database. Unfortunately, it is unclear how to do this from the doc.

Here's what worked for me:

I defined a common `mysql.conf` as shown below in a module that every service depends on.

```
# https://www.lagomframework.com/documentation/1.4.x/scala/PersistentEntityRDBMS.html#Table-creation
lagom.persistence.jdbc.create-tables.auto = true

# service.database is a configuration that must be set to a well-formed name for a MySQL user and database
lagom.persistence.read-side.jdbc.slick.jndiDbName = ${service.database}DB

play.db.pool=hikaricp

#

# See com.lightbend.lagom/lagom-persistence-jdbc-core_2.12/jars/lagom-persistence-jdbc-core_2.12-1.4.11.jar!/reference.conf
jdbc-defaults.slick {
  profile = "slick.jdbc.MySQLProfile$"
  url = "jdbc:mysql://localhost:3306/"${service.database}"?autoReconnect=true&serverTimezone=PST8PDT"
  jndiName = ${service.database}DS
  jndiDbName = ${service.database}DB
  driver = "com.mysql.cj.jdbc.Driver"
}


db.default {
  jndiName = ${service.database}DS
  jndiDbName = ${service.database}DB
  driver = "com.mysql.cj.jdbc.Driver"
  # Timezone: https://knowledgebase.progress.com/articles/Article/MySQL-8-JDBC-drivers-affecting-date-time-field-data
  url = "jdbc:mysql://localhost:3306/"${service.database}"?autoReconnect=true&serverTimezone=PST8PDT"
  username = ${service.database}
  password = ${?MYSQL_PASSWORD}
}
```

For example, a service named `ServiceA`, would have its `application.conf` like this:

```
service.database = "ServiceA"
include "mysql.conf"
```

The definition of a service (i.e., `Entity`, `State`, `Command`, `ServiceRegistry`) is independent of the persistence backend; only the `Loader` & `Application` is slightly different due to the persistence dependencies that need to be injected (compile or runtime).

It is important to note that if each service has a dedicated MySQL database and that all these MySQL databases are on the same MySQL server, then it is necessary to also have a database-specific MySQL user as well.

The documentation should also explain that it is necessary to create the MySQL database per se and corresponding user; this can be done like this:

```
mysql -u root -p
```

For a service named `{serviceName}`, I chose to create a MySQL user `{serviceName}` and a MySQL database `{serviceName}` as shown below, replacing `{servicePassword}` with `$MYSQL_PASSWORD`.

```
CREATE DATABASE `{serviceName}`;
CREATE USER '{serviceName}'@'localhost' IDENTIFIED BY '{servicePassword}';
GRANT ALL PRIVILEGES ON `{serviceName}`.* TO '{serviceName}'@'localhost';
```

Since I have each service with 2 variants, Cassandra and MySQL, in the same SBT project,
I couldn't use `runAll` to start everything. So instead, I wrote simple SBT tasks to start services
with either Cassandra or MySQL persistence.

For example, with 2 services, `ServiceA` and `ServiceB`, each has 2 SBT projects
for Cassandra and MySQL loaders, e.g., `ServiceA-cassandra`, `ServiceA-mysql`.

The start tasks are as follows:

```
lazy val startCassandra = taskKey[Unit]("Start the services with Cassandra persistence")
lazy val startMySQL = taskKey[Unit]("Start the services with MySQL persistence")

startCassandra := Def.sequential(
   lagomRun in `ServiceA-cassandra`,
   lagomRun in `ServiceB-cassandra`,
   Def.task {
      val log = state.value.log
      val consoleHelper = new ConsoleHelper(new Colors("sbt.log.noformat"))
      log.info(s"All services started, press any key to exit...")
      consoleHelper.blockUntilExit()
    }
  )
  .value

startMySQL := Def.sequential(
   lagomRun in `ServiceA-mysql`,
   lagomRun in `ServiceB-mysql`,
   Def.task {
      val log = state.value.log
      val consoleHelper = new ConsoleHelper(new Colors("sbt.log.noformat"))
      log.info(s"All services started, press any key to exit...")
      consoleHelper.blockUntilExit()
    }
  )
  .value
```

The point here is that it's been a while since this issue has been opened.
While there are perhaps a few things that could be improved in the plugin w.r.t. configuration settings that are required -- e.g., I'm not really sure about the need for both `jdbc-defaults.slick` and `db.default` -- it seems to me that what's missing is documentation. I hope the above may be helpful for that purpose.

**Comment by octonato** [comment]
I'm working on a PR to do this, but not as auto-creation via property, but using an utility class that we can run at test start-up (or application).

**Comment by ennru** [comment]
#465 introduced the `SchemaUtils` (for release 5.0.0) which is mostly targeted to simplify testing setups.
We will not enable auto-creation of the database schema by default. If that it the correct choice for you application, you may use `SchemaUtils` to do that.
